### ISSUE TITLE
[feat] Add firebase and firestore support 

### ISSUE THREAD

**Issue by ayaankhan98** [ayaankhan98/Note_App#3]
Add firebase and firestore support to sync notes on different devices

**Comment by yaderson** [comment]
hi, i can work on this but i need more info on how it should work

**Comment by ayaankhan98** [comment]
@yaderson yes sure you can start, i would be happy to answer your queries

**Comment by akhil2000mittal** [comment]
Hi, if it is still not done, I will be happy to help you out with this

**Comment by ayaankhan98** [comment]
@akhil2000mittal sure you can proceede.

**Comment by akhil2000mittal** [comment]
@ayaankhan98 but for this we have to make a firebase project and it will be appreciated if you make a firebase account with your account and then add me as a editor
